# Generated by Django 5.2.7 on 2025-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_realestateproject_plotinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotinventory',
            name='price',
            field=models.CharField(help_text='Example: 80L, 30L', max_length=20),
        ),
    ]
