# Generated by Django 5.2.7 on 2025-10-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0003_alter_plotinventory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateproject',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='PlotInventory',
        ),
        migrations.DeleteModel(
            name='RealEstateProject',
        ),
    ]
