# Generated by Django 5.2.7 on 2025-10-14 12:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0004_remove_realestateproject_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='projects/banner_images/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='projects/brochures/')),
                ('map_layout', models.ImageField(blank=True, null=True, upload_to='projects/map_layouts/')),
                ('total_plots', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('inventory_excel', models.FileField(blank=True, null=True, upload_to='projects/inventory_excels/')),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage for this project', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='admin_part.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='PlotInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=50)),
                ('size', models.CharField(help_text='Example: 30x40 ft', max_length=100)),
                ('area_sq', models.DecimalField(decimal_places=2, help_text='Total area in sq. ft', max_digits=10)),
                ('price', models.CharField(help_text='Example: 80L, 30L', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='admin_part.realestateproject')),
            ],
        ),
    ]
