# Generated by Django 5.2.7 on 2025-10-16 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0005_realestateproject_plotinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='admin_part.realestateproject')),
            ],
            options={
                'verbose_name': 'Project Highlight',
                'verbose_name_plural': 'Project Highlights',
            },
        ),
    ]
