# Generated by Django 5.2.7 on 2025-10-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0006_projecthighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateproject',
            name='status',
            field=models.CharField(choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing')], default='upcoming', max_length=50),
        ),
    ]
