# Generated by Django 5.2.7 on 2025-10-28 05:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0007_alter_realestateproject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPaymentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(help_text='Name of the payment phase/activity', max_length=255)),
                ('payment_percentage', models.DecimalField(decimal_places=2, help_text='Payment percentage for this phase', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the payment phase')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_phases', to='admin_part.realestateproject')),
            ],
            options={
                'verbose_name': 'Project Payment Phase',
                'verbose_name_plural': 'Project Payment Phases',
                'ordering': ['order'],
                'unique_together': {('project', 'activity')},
            },
        ),
    ]
