# Generated by Django 5.2.7 on 2025-10-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0008_projectpaymentphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpaymentphase',
            name='due',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('30_days', 'Within 30 Days'), ('60_days', 'Within 60 Days'), ('90_days', 'Within 90 Days'), ('120_days', 'Within 120 Days'), ('custom', 'Custom Duration')], default='immediate', help_text='When the payment is due', max_length=50),
        ),
    ]
