# Generated by Django 5.2.7 on 2025-11-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0009_projectpaymentphase_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproject',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_projects', to='admin_part.projectpaymentphase'),
        ),
    ]
