# Generated by Django 5.2.7 on 2025-12-02 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_realestateproject_current_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpaymentphase',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='projectpaymentphase',
            name='payment_type',
            field=models.CharField(choices=[('full_payment', 'Full Payment'), ('phase_wise', 'Phase Wise Payment')], default='phase_wise', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectpaymentphase',
            name='activity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpaymentphase',
            name='due',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('30_days', 'Within 30 Days'), ('60_days', 'Within 60 Days'), ('90_days', 'Within 90 Days'), ('120_days', 'Within 120 Days'), ('custom', 'Custom Duration')], default='immediate', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectpaymentphase',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectpaymentphase',
            name='payment_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
