# Generated by Django 5.2.7 on 2026-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0011_alter_projectpaymentphase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpaymentphase',
            name='custom_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text="Custom duration in days (only used when due='custom')", null=True),
        ),
    ]
