# Generated by Django 5.2.7 on 2026-02-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0012_projectpaymentphase_custom_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotinventory',
            name='type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', help_text='Plot type: Residential or Commercial', max_length=50),
        ),
    ]
