# Generated by Django 5.2.7 on 2025-10-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('visited', 'Visited'), ('booking', 'Booking'), ('payment', 'Payment')], default='new', help_text='Lead type (e.g., new, visited, booking, payment)', max_length=20),
        ),
    ]
