# Generated by Django 5.2.7 on 2025-10-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0006_projecthighlight'),
        ('agents', '0002_lead_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='project',
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects the lead is interested in', related_name='leads', to='admin_part.realestateproject'),
        ),
    ]
