# Generated by Django 5.2.7 on 2025-10-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0009_projectpaymentphase_due'),
        ('agents', '0003_remove_lead_project_lead_city_lead_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('visited', 'Visited'), ('booked', 'Booked'), ('payment_done', 'Payment Done'), ('closed', 'Closed')], default='interested', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_projects', to='agents.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_leads', to='admin_part.realestateproject')),
            ],
            options={
                'unique_together': {('lead', 'project')},
            },
        ),
    ]
