# Generated by Django 5.2.7 on 2025-10-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_leadproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='projects',
        ),
    ]
