# Generated by Django 5.2.7 on 2025-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0009_projectpaymentphase_due'),
        ('agents', '0005_remove_lead_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects the lead is interested in', related_name='leads', through='agents.LeadProject', to='admin_part.realestateproject'),
        ),
    ]
