# Generated by Django 5.2.7 on 2025-10-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0009_projectpaymentphase_due'),
        ('agents', '0006_lead_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked'), ('payment_done', 'Payment Done'), ('cancelled', 'Cancelled')], default='reserved', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lead_plots', to=settings.AUTH_USER_MODEL)),
                ('lead_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plots', to='agents.leadproject')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to='admin_part.plotinventory')),
            ],
            options={
                'verbose_name': 'Lead Plot Assignment',
                'verbose_name_plural': 'Lead Plot Assignments',
                'unique_together': {('lead_project', 'plot')},
            },
        ),
    ]
