# Generated by Django 5.2.7 on 2025-11-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_leadplotassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='type',
        ),
    ]
