# Generated by Django 5.2.7 on 2025-11-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_lead_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadplotassignment',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('visited', 'Visited'), ('booked', 'Booked'), ('payment_done', 'Payment Done'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='reserved', max_length=50),
        ),
        migrations.AlterField(
            model_name='leadproject',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('visited', 'Visited'), ('in_progress', 'In Progress'), ('booked', 'Booked'), ('payment_done', 'Payment Done'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='interested', max_length=50),
        ),
    ]
