# Generated by Django 5.2.7 on 2025-11-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_lead_status_alter_leadplotassignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadplotassignment',
            name='order_id',
            field=models.CharField(blank=True, help_text='Used to group multiple plots added together in a single order', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leadplotassignment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='leadproject',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('visited', 'Visited'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='interested', max_length=50),
        ),
    ]
