# Generated by Django 5.2.7 on 2025-11-06 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_realestateproject_current_phase'),
        ('agents', '0010_leadplotassignment_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPlotPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('lead_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agents.leadplotassignment')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_plot_payments', to='admin_part.projectpaymentphase')),
            ],
            options={
                'unique_together': {('lead_plot', 'phase')},
            },
        ),
    ]
