# Generated by Django 5.2.7 on 2025-11-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_leadplotpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadplotpayment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
