# Generated by Django 5.2.7 on 2025-11-08 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_realestateproject_current_phase'),
        ('agents', '0012_leadplotpayment_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdrawable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdrawn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('lead_plot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='agents.leadplotassignment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='admin_part.realestateproject')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='agents.agentcommission')),
            ],
            options={
                'verbose_name': 'Commission Withdrawal',
                'verbose_name_plural': 'Commission Withdrawals',
            },
        ),
    ]
