# Generated by Django 5.2.7 on 2025-11-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_alter_lead_options_alter_lead_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadproject',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_projects', to='agents.customer'),
        ),
        migrations.AlterField(
            model_name='leadproject',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='interested', max_length=50),
        ),
    ]
