# Generated by Django 5.2.7 on 2025-12-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_realestateproject_current_phase'),
        ('agents', '0015_leadproject_customer_alter_leadproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='leads', through='agents.LeadProject', to='admin_part.realestateproject'),
        ),
        migrations.AlterField(
            model_name='leadproject',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_projects', to='agents.lead'),
        ),
    ]
