# Generated by Django 5.2.7 on 2025-12-02 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_realestateproject_current_phase'),
        ('agents', '0016_alter_lead_projects_alter_leadproject_lead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadproject',
            unique_together={('customer', 'project')},
        ),
        migrations.AddField(
            model_name='leadplotassignment',
            name='is_negotiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadplotassignment',
            name='negotiated_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadplotassignment',
            name='negotiated_price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='leadplotassignment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='leadproject',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_projects', to='agents.lead'),
        ),
    ]
