# Generated by Django 5.2.7 on 2025-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_alter_leadproject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadproject',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('phase', 'Phase Wise Payment')], default='phase', max_length=20),
        ),
    ]
