# Generated by Django 5.2.7 on 2025-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_leadproject_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadplotassignment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('full_payment', 'Full Payment'), ('phase_wise', 'Phase Wise Payment')], default='phase_wise', max_length=20, null=True),
        ),
    ]
