# Generated by Django 5.2.7 on 2025-12-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_leadplotassignment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadplotpayment',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Invoice or bill number for this payment', max_length=100, null=True),
        ),
    ]
