# Generated by Django 5.2.7 on 2025-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_leadplotpayment_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcommission',
            name='matured_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount available after 30-day maturity', max_digits=12),
        ),
    ]
