# Generated by Django 5.2.7 on 2026-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_agentcommission_matured_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadplotassignment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=50),
        ),
    ]
