# Generated by Django 5.2.7 on 2026-02-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_alter_leadplotassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternative_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='alternative_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
