# Generated by Django 5.2.7 on 2025-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_customuser_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adhar_card',
            field=models.FileField(blank=True, max_length=12, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_card',
            field=models.FileField(blank=True, max_length=10, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
