# Generated by Django 5.2.7 on 2025-11-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_customuser_adhar_card_customuser_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adhar_card',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documents/adhar/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_card',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documents/pan/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/'),
        ),
    ]
